/** TradingView symbol mapping and widget helpers. */

export type TvGroup = "Stocks" | "ETFs" | "Indices" | "Crypto" | "Forex" | "NGX";

export type TvSymbol = {
  tv:          string;    // exchange:symbol used by TradingView widget
  label:       string;    // display ticker
  group:       TvGroup;
  description: string;
};

export const TV_SYMBOLS: TvSymbol[] = [
  // ── US Stocks — Mega Cap ─────────────────────────────────────────────────────
  { tv: "NASDAQ:AAPL",  label: "AAPL",  group: "Stocks", description: "Apple Inc." },
  { tv: "NASDAQ:MSFT",  label: "MSFT",  group: "Stocks", description: "Microsoft Corp." },
  { tv: "NASDAQ:NVDA",  label: "NVDA",  group: "Stocks", description: "NVIDIA Corp." },
  { tv: "NASDAQ:AMZN",  label: "AMZN",  group: "Stocks", description: "Amazon.com Inc." },
  { tv: "NASDAQ:GOOGL", label: "GOOGL", group: "Stocks", description: "Alphabet Inc." },
  { tv: "NASDAQ:META",  label: "META",  group: "Stocks", description: "Meta Platforms Inc." },
  { tv: "NASDAQ:TSLA",  label: "TSLA",  group: "Stocks", description: "Tesla Inc." },
  { tv: "NYSE:JPM",     label: "JPM",   group: "Stocks", description: "JPMorgan Chase" },
  { tv: "NYSE:V",       label: "V",     group: "Stocks", description: "Visa Inc." },
  { tv: "NYSE:UNH",     label: "UNH",   group: "Stocks", description: "UnitedHealth Group" },
  { tv: "NYSE:LLY",     label: "LLY",   group: "Stocks", description: "Eli Lilly" },
  { tv: "NASDAQ:AVGO",  label: "AVGO",  group: "Stocks", description: "Broadcom Inc." },
  { tv: "NYSE:XOM",     label: "XOM",   group: "Stocks", description: "Exxon Mobil" },
  { tv: "NYSE:MA",      label: "MA",    group: "Stocks", description: "Mastercard Inc." },
  { tv: "NYSE:HD",      label: "HD",    group: "Stocks", description: "Home Depot" },
  { tv: "NYSE:PG",      label: "PG",    group: "Stocks", description: "Procter & Gamble" },
  { tv: "NASDAQ:COST",  label: "COST",  group: "Stocks", description: "Costco Wholesale" },
  { tv: "NYSE:JNJ",     label: "JNJ",   group: "Stocks", description: "Johnson & Johnson" },
  { tv: "NYSE:MRK",     label: "MRK",   group: "Stocks", description: "Merck & Co." },
  { tv: "NYSE:CVX",     label: "CVX",   group: "Stocks", description: "Chevron Corp." },
  // ── US Stocks — Large Cap ────────────────────────────────────────────────────
  { tv: "NYSE:ABBV",    label: "ABBV",  group: "Stocks", description: "AbbVie Inc." },
  { tv: "NYSE:BAC",     label: "BAC",   group: "Stocks", description: "Bank of America" },
  { tv: "NYSE:KO",      label: "KO",    group: "Stocks", description: "Coca-Cola Co." },
  { tv: "NASDAQ:PEP",   label: "PEP",   group: "Stocks", description: "PepsiCo Inc." },
  { tv: "NASDAQ:NFLX",  label: "NFLX",  group: "Stocks", description: "Netflix Inc." },
  { tv: "NYSE:TMO",     label: "TMO",   group: "Stocks", description: "Thermo Fisher Scientific" },
  { tv: "NYSE:ORCL",    label: "ORCL",  group: "Stocks", description: "Oracle Corp." },
  { tv: "NASDAQ:AMD",   label: "AMD",   group: "Stocks", description: "Advanced Micro Devices" },
  { tv: "NYSE:CRM",     label: "CRM",   group: "Stocks", description: "Salesforce Inc." },
  { tv: "NASDAQ:CSCO",  label: "CSCO",  group: "Stocks", description: "Cisco Systems" },
  { tv: "NYSE:ACN",     label: "ACN",   group: "Stocks", description: "Accenture PLC" },
  { tv: "NYSE:MCD",     label: "MCD",   group: "Stocks", description: "McDonald's Corp." },
  { tv: "NYSE:LIN",     label: "LIN",   group: "Stocks", description: "Linde PLC" },
  { tv: "NASDAQ:ADBE",  label: "ADBE",  group: "Stocks", description: "Adobe Inc." },
  { tv: "NASDAQ:INTC",  label: "INTC",  group: "Stocks", description: "Intel Corp." },
  { tv: "NYSE:WMT",     label: "WMT",   group: "Stocks", description: "Walmart Inc." },
  { tv: "NYSE:DHR",     label: "DHR",   group: "Stocks", description: "Danaher Corp." },
  { tv: "NASDAQ:TXN",   label: "TXN",   group: "Stocks", description: "Texas Instruments" },
  { tv: "NYSE:IBM",     label: "IBM",   group: "Stocks", description: "IBM Corp." },
  { tv: "NASDAQ:INTU",  label: "INTU",  group: "Stocks", description: "Intuit Inc." },
  // ── US Stocks — Growth / Tech ─────────────────────────────────────────────────
  { tv: "NASDAQ:BKNG",  label: "BKNG",  group: "Stocks", description: "Booking Holdings" },
  { tv: "NASDAQ:ISRG",  label: "ISRG",  group: "Stocks", description: "Intuitive Surgical" },
  { tv: "NYSE:SPGI",    label: "SPGI",  group: "Stocks", description: "S&P Global Inc." },
  { tv: "NYSE:NOW",     label: "NOW",   group: "Stocks", description: "ServiceNow Inc." },
  { tv: "NASDAQ:PANW",  label: "PANW",  group: "Stocks", description: "Palo Alto Networks" },
  { tv: "NYSE:SNOW",    label: "SNOW",  group: "Stocks", description: "Snowflake Inc." },
  { tv: "NYSE:PLTR",    label: "PLTR",  group: "Stocks", description: "Palantir Technologies" },
  { tv: "NYSE:UBER",    label: "UBER",  group: "Stocks", description: "Uber Technologies" },
  { tv: "NASDAQ:COIN",  label: "COIN",  group: "Stocks", description: "Coinbase Global" },
  { tv: "NYSE:SHOP",    label: "SHOP",  group: "Stocks", description: "Shopify Inc." },
  { tv: "NYSE:SQ",      label: "SQ",    group: "Stocks", description: "Block Inc." },
  { tv: "NASDAQ:PYPL",  label: "PYPL",  group: "Stocks", description: "PayPal Holdings" },
  { tv: "NYSE:SNAP",    label: "SNAP",  group: "Stocks", description: "Snap Inc." },
  { tv: "NYSE:RBLX",    label: "RBLX",  group: "Stocks", description: "Roblox Corp." },
  { tv: "NASDAQ:ABNB",  label: "ABNB",  group: "Stocks", description: "Airbnb Inc." },
  { tv: "NASDAQ:DKNG",  label: "DKNG",  group: "Stocks", description: "DraftKings Inc." },
  { tv: "NASDAQ:HOOD",  label: "HOOD",  group: "Stocks", description: "Robinhood Markets" },
  { tv: "NASDAQ:ARM",   label: "ARM",   group: "Stocks", description: "Arm Holdings PLC" },
  { tv: "NASDAQ:SMCI",  label: "SMCI",  group: "Stocks", description: "Super Micro Computer" },
  { tv: "NYSE:BABA",    label: "BABA",  group: "Stocks", description: "Alibaba Group" },
  // ── US Stocks — Financials / Industrials ──────────────────────────────────────
  { tv: "NYSE:GS",      label: "GS",    group: "Stocks", description: "Goldman Sachs" },
  { tv: "NYSE:MS",      label: "MS",    group: "Stocks", description: "Morgan Stanley" },
  { tv: "NYSE:BLK",     label: "BLK",   group: "Stocks", description: "BlackRock Inc." },
  { tv: "NYSE:AXP",     label: "AXP",   group: "Stocks", description: "American Express" },
  { tv: "NYSE:C",       label: "C",     group: "Stocks", description: "Citigroup Inc." },
  { tv: "NYSE:DE",      label: "DE",    group: "Stocks", description: "Deere & Company" },
  { tv: "NYSE:CAT",     label: "CAT",   group: "Stocks", description: "Caterpillar Inc." },
  { tv: "NASDAQ:HON",   label: "HON",   group: "Stocks", description: "Honeywell International" },
  { tv: "NYSE:RTX",     label: "RTX",   group: "Stocks", description: "RTX Corp." },
  { tv: "NYSE:GE",      label: "GE",    group: "Stocks", description: "GE Aerospace" },
  { tv: "NYSE:ETN",     label: "ETN",   group: "Stocks", description: "Eaton Corp." },
  { tv: "NYSE:LMT",     label: "LMT",   group: "Stocks", description: "Lockheed Martin" },
  { tv: "NYSE:BA",      label: "BA",    group: "Stocks", description: "Boeing Co." },
  { tv: "NYSE:NEE",     label: "NEE",   group: "Stocks", description: "NextEra Energy" },
  { tv: "NYSE:T",       label: "T",     group: "Stocks", description: "AT&T Inc." },
  { tv: "NASDAQ:AMGN",  label: "AMGN",  group: "Stocks", description: "Amgen Inc." },
  { tv: "NASDAQ:GILD",  label: "GILD",  group: "Stocks", description: "Gilead Sciences" },
  { tv: "NASDAQ:SBUX",  label: "SBUX",  group: "Stocks", description: "Starbucks Corp." },
  { tv: "NYSE:BX",      label: "BX",    group: "Stocks", description: "Blackstone Inc." },
  { tv: "NYSE:DIS",     label: "DIS",   group: "Stocks", description: "Walt Disney Co." },
  { tv: "NYSE:PLD",     label: "PLD",   group: "Stocks", description: "Prologis Inc." },
  { tv: "NYSE:PM",      label: "PM",    group: "Stocks", description: "Philip Morris International" },
  { tv: "NYSE:ABT",     label: "ABT",   group: "Stocks", description: "Abbott Laboratories" },
  { tv: "NASDAQ:MDLZ",  label: "MDLZ",  group: "Stocks", description: "Mondelez International" },
  { tv: "NYSE:MO",      label: "MO",    group: "Stocks", description: "Altria Group" },
  { tv: "NASDAQ:ADI",   label: "ADI",   group: "Stocks", description: "Analog Devices Inc." },
  // ── US Stocks — Semiconductors / Hardware ────────────────────────────────────
  { tv: "NASDAQ:QCOM",  label: "QCOM",  group: "Stocks", description: "Qualcomm Inc." },
  { tv: "NASDAQ:MU",    label: "MU",    group: "Stocks", description: "Micron Technology" },
  { tv: "NASDAQ:LRCX",  label: "LRCX",  group: "Stocks", description: "Lam Research Corp." },
  { tv: "NASDAQ:AMAT",  label: "AMAT",  group: "Stocks", description: "Applied Materials" },
  { tv: "NASDAQ:KLAC",  label: "KLAC",  group: "Stocks", description: "KLA Corp." },
  { tv: "NASDAQ:MRVL",  label: "MRVL",  group: "Stocks", description: "Marvell Technology" },
  { tv: "NYSE:ANET",    label: "ANET",  group: "Stocks", description: "Arista Networks" },
  { tv: "NYSE:DELL",    label: "DELL",  group: "Stocks", description: "Dell Technologies" },
  { tv: "NYSE:HPQ",     label: "HPQ",   group: "Stocks", description: "HP Inc." },
  { tv: "NASDAQ:MSTR",  label: "MSTR",  group: "Stocks", description: "MicroStrategy Inc." },
  // ── US Stocks — Cloud / Software / AI ────────────────────────────────────────
  { tv: "NYSE:NET",     label: "NET",   group: "Stocks", description: "Cloudflare Inc." },
  { tv: "NASDAQ:CRWD",  label: "CRWD",  group: "Stocks", description: "CrowdStrike Holdings" },
  { tv: "NASDAQ:ZS",    label: "ZS",    group: "Stocks", description: "Zscaler Inc." },
  { tv: "NASDAQ:DDOG",  label: "DDOG",  group: "Stocks", description: "Datadog Inc." },
  { tv: "NASDAQ:MDB",   label: "MDB",   group: "Stocks", description: "MongoDB Inc." },
  { tv: "NASDAQ:WDAY",  label: "WDAY",  group: "Stocks", description: "Workday Inc." },
  { tv: "NASDAQ:TTD",   label: "TTD",   group: "Stocks", description: "The Trade Desk" },
  { tv: "NYSE:TWLO",    label: "TWLO",  group: "Stocks", description: "Twilio Inc." },
  { tv: "NASDAQ:APP",   label: "APP",   group: "Stocks", description: "AppLovin Corp." },
  { tv: "NASDAQ:DUOL",  label: "DUOL",  group: "Stocks", description: "Duolingo Inc." },
  // ── US Stocks — Consumer / Retail ────────────────────────────────────────────
  { tv: "NYSE:NKE",     label: "NKE",   group: "Stocks", description: "Nike Inc." },
  { tv: "NYSE:LOW",     label: "LOW",   group: "Stocks", description: "Lowe's Companies" },
  { tv: "NYSE:TGT",     label: "TGT",   group: "Stocks", description: "Target Corp." },
  { tv: "NYSE:F",       label: "F",     group: "Stocks", description: "Ford Motor Co." },
  { tv: "NYSE:GM",      label: "GM",    group: "Stocks", description: "General Motors" },
  { tv: "NASDAQ:LULU",  label: "LULU",  group: "Stocks", description: "Lululemon Athletica" },
  { tv: "NYSE:ONON",    label: "ONON",  group: "Stocks", description: "On Holding AG" },
  { tv: "NASDAQ:LYFT",  label: "LYFT",  group: "Stocks", description: "Lyft Inc." },
  { tv: "NASDAQ:RIVN",  label: "RIVN",  group: "Stocks", description: "Rivian Automotive" },
  { tv: "NASDAQ:CELH",  label: "CELH",  group: "Stocks", description: "Celsius Holdings" },
  { tv: "NASDAQ:EBAY",  label: "EBAY",  group: "Stocks", description: "eBay Inc." },
  { tv: "NASDAQ:WYNN",  label: "WYNN",  group: "Stocks", description: "Wynn Resorts" },
  { tv: "NYSE:LVS",     label: "LVS",   group: "Stocks", description: "Las Vegas Sands" },
  { tv: "NYSE:NCLH",    label: "NCLH",  group: "Stocks", description: "Norwegian Cruise Line" },
  // ── US Stocks — Healthcare ────────────────────────────────────────────────────
  { tv: "NYSE:PFE",     label: "PFE",   group: "Stocks", description: "Pfizer Inc." },
  { tv: "NYSE:BMY",     label: "BMY",   group: "Stocks", description: "Bristol-Myers Squibb" },
  { tv: "NYSE:CVS",     label: "CVS",   group: "Stocks", description: "CVS Health Corp." },
  { tv: "NYSE:MDT",     label: "MDT",   group: "Stocks", description: "Medtronic PLC" },
  { tv: "NYSE:BSX",     label: "BSX",   group: "Stocks", description: "Boston Scientific" },
  { tv: "NYSE:ZTS",     label: "ZTS",   group: "Stocks", description: "Zoetis Inc." },
  { tv: "NASDAQ:DXCM",  label: "DXCM",  group: "Stocks", description: "Dexcom Inc." },
  { tv: "NASDAQ:MRNA",  label: "MRNA",  group: "Stocks", description: "Moderna Inc." },
  { tv: "NYSE:CI",      label: "CI",    group: "Stocks", description: "Cigna Group" },
  { tv: "NYSE:EW",      label: "EW",    group: "Stocks", description: "Edwards Lifesciences" },
  // ── US Stocks — Financials (expanded) ────────────────────────────────────────
  { tv: "NYSE:WFC",     label: "WFC",   group: "Stocks", description: "Wells Fargo & Co." },
  { tv: "NYSE:USB",     label: "USB",   group: "Stocks", description: "U.S. Bancorp" },
  { tv: "NYSE:COF",     label: "COF",   group: "Stocks", description: "Capital One Financial" },
  { tv: "NYSE:SCHW",    label: "SCHW",  group: "Stocks", description: "Charles Schwab Corp." },
  { tv: "NASDAQ:CME",   label: "CME",   group: "Stocks", description: "CME Group Inc." },
  { tv: "NYSE:MCO",     label: "MCO",   group: "Stocks", description: "Moody's Corp." },
  { tv: "NYSE:FIS",     label: "FIS",   group: "Stocks", description: "Fidelity National Info." },
  { tv: "NASDAQ:FISV",  label: "FISV",  group: "Stocks", description: "Fiserv Inc." },
  { tv: "NYSE:PNC",     label: "PNC",   group: "Stocks", description: "PNC Financial Services" },
  { tv: "NYSE:TFC",     label: "TFC",   group: "Stocks", description: "Truist Financial Corp." },
  // ── US Stocks — Energy / Materials ───────────────────────────────────────────
  { tv: "NYSE:SLB",     label: "SLB",   group: "Stocks", description: "SLB (Schlumberger)" },
  { tv: "NYSE:COP",     label: "COP",   group: "Stocks", description: "ConocoPhillips" },
  { tv: "NYSE:EOG",     label: "EOG",   group: "Stocks", description: "EOG Resources" },
  { tv: "NYSE:DVN",     label: "DVN",   group: "Stocks", description: "Devon Energy" },
  { tv: "NYSE:MPC",     label: "MPC",   group: "Stocks", description: "Marathon Petroleum" },
  { tv: "NYSE:VLO",     label: "VLO",   group: "Stocks", description: "Valero Energy" },
  { tv: "NYSE:PSX",     label: "PSX",   group: "Stocks", description: "Phillips 66" },
  { tv: "NYSE:FCX",     label: "FCX",   group: "Stocks", description: "Freeport-McMoRan" },
  { tv: "NYSE:NEM",     label: "NEM",   group: "Stocks", description: "Newmont Corp." },
  { tv: "NYSE:HAL",     label: "HAL",   group: "Stocks", description: "Halliburton Co." },
  // ── US Stocks — Industrials / Transport ──────────────────────────────────────
  { tv: "NYSE:UPS",     label: "UPS",   group: "Stocks", description: "UPS Inc." },
  { tv: "NYSE:FDX",     label: "FDX",   group: "Stocks", description: "FedEx Corp." },
  { tv: "NYSE:WM",      label: "WM",    group: "Stocks", description: "Waste Management Inc." },
  { tv: "NYSE:UNP",     label: "UNP",   group: "Stocks", description: "Union Pacific Corp." },
  { tv: "NYSE:MMM",     label: "MMM",   group: "Stocks", description: "3M Company" },
  { tv: "NYSE:EMR",     label: "EMR",   group: "Stocks", description: "Emerson Electric" },
  { tv: "NYSE:ITW",     label: "ITW",   group: "Stocks", description: "Illinois Tool Works" },
  { tv: "NASDAQ:AXON",  label: "AXON",  group: "Stocks", description: "Axon Enterprise" },
  { tv: "NYSE:ROK",     label: "ROK",   group: "Stocks", description: "Rockwell Automation" },
  { tv: "NYSE:GNRC",    label: "GNRC",  group: "Stocks", description: "Generac Holdings" },
  // ── US Stocks — Real Estate / Utilities ──────────────────────────────────────
  { tv: "NYSE:AMT",     label: "AMT",   group: "Stocks", description: "American Tower Corp." },
  { tv: "NASDAQ:EQIX",  label: "EQIX",  group: "Stocks", description: "Equinix Inc." },
  { tv: "NYSE:CCI",     label: "CCI",   group: "Stocks", description: "Crown Castle Inc." },
  { tv: "NYSE:SPG",     label: "SPG",   group: "Stocks", description: "Simon Property Group" },
  { tv: "NYSE:O",       label: "O",     group: "Stocks", description: "Realty Income Corp." },
  { tv: "NYSE:PSA",     label: "PSA",   group: "Stocks", description: "Public Storage" },
  { tv: "NYSE:DUK",     label: "DUK",   group: "Stocks", description: "Duke Energy Corp." },
  { tv: "NYSE:SO",      label: "SO",    group: "Stocks", description: "Southern Company" },
  { tv: "NYSE:DLR",     label: "DLR",   group: "Stocks", description: "Digital Realty Trust" },
  { tv: "NASDAQ:AEP",   label: "AEP",   group: "Stocks", description: "American Electric Power" },
  // ── US Stocks — Media / Streaming / Other ────────────────────────────────────
  { tv: "NYSE:SPOT",    label: "SPOT",  group: "Stocks", description: "Spotify Technology" },
  { tv: "NASDAQ:ROKU",  label: "ROKU",  group: "Stocks", description: "Roku Inc." },
  { tv: "NYSE:PINS",    label: "PINS",  group: "Stocks", description: "Pinterest Inc." },
  { tv: "NASDAQ:ZM",    label: "ZM",    group: "Stocks", description: "Zoom Video Communications" },
  { tv: "NASDAQ:WBD",   label: "WBD",   group: "Stocks", description: "Warner Bros. Discovery" },
  { tv: "NYSE:PATH",    label: "PATH",  group: "Stocks", description: "UiPath Inc." },
  { tv: "NYSE:JOBY",    label: "JOBY",  group: "Stocks", description: "Joby Aviation" },
  { tv: "NYSE:ACHR",    label: "ACHR",  group: "Stocks", description: "Archer Aviation" },
  // ── International / ADRs ─────────────────────────────────────────────────────
  { tv: "NYSE:TSM",     label: "TSM",   group: "Stocks", description: "Taiwan Semiconductor" },
  { tv: "NASDAQ:ASML",  label: "ASML",  group: "Stocks", description: "ASML Holding NV" },
  { tv: "NYSE:SAP",     label: "SAP",   group: "Stocks", description: "SAP SE" },
  { tv: "NYSE:TM",      label: "TM",    group: "Stocks", description: "Toyota Motor Corp." },
  { tv: "NASDAQ:AZN",   label: "AZN",   group: "Stocks", description: "AstraZeneca PLC" },
  { tv: "NYSE:NVS",     label: "NVS",   group: "Stocks", description: "Novartis AG" },
  { tv: "NYSE:SHEL",    label: "SHEL",  group: "Stocks", description: "Shell PLC" },
  { tv: "NYSE:BHP",     label: "BHP",   group: "Stocks", description: "BHP Group Ltd." },
  { tv: "NASDAQ:SNY",   label: "SNY",   group: "Stocks", description: "Sanofi SA" },
  { tv: "NYSE:RIO",     label: "RIO",   group: "Stocks", description: "Rio Tinto PLC" },
  { tv: "NYSE:BP",      label: "BP",    group: "Stocks", description: "BP PLC" },
  { tv: "NYSE:TTE",     label: "TTE",   group: "Stocks", description: "TotalEnergies SE" },
  { tv: "NYSE:HSBC",    label: "HSBC",  group: "Stocks", description: "HSBC Holdings PLC" },
  { tv: "NYSE:NVO",     label: "NVO",   group: "Stocks", description: "Novo Nordisk A/S" },
  { tv: "NYSE:DEO",     label: "DEO",   group: "Stocks", description: "Diageo PLC" },
  { tv: "NYSE:BTI",     label: "BTI",   group: "Stocks", description: "British American Tobacco" },
  { tv: "NYSE:UL",      label: "UL",    group: "Stocks", description: "Unilever PLC" },
  { tv: "NYSE:SE",      label: "SE",    group: "Stocks", description: "Sea Limited" },
  { tv: "NYSE:PBR",     label: "PBR",   group: "Stocks", description: "Petrobras" },
  { tv: "NYSE:VALE",    label: "VALE",  group: "Stocks", description: "Vale SA" },
  { tv: "NASDAQ:ERIC",  label: "ERIC",  group: "Stocks", description: "Ericsson" },
  { tv: "NYSE:NOK",     label: "NOK",   group: "Stocks", description: "Nokia Corp." },

  // ── ETFs — Broad Market US ───────────────────────────────────────────────────
  { tv: "AMEX:SPY",     label: "SPY",   group: "ETFs", description: "SPDR S&P 500 ETF" },
  { tv: "AMEX:IVV",     label: "IVV",   group: "ETFs", description: "iShares Core S&P 500" },
  { tv: "AMEX:VOO",     label: "VOO",   group: "ETFs", description: "Vanguard S&P 500 ETF" },
  { tv: "AMEX:SPLG",    label: "SPLG",  group: "ETFs", description: "SPDR Portfolio S&P 500" },
  { tv: "NASDAQ:QQQ",   label: "QQQ",   group: "ETFs", description: "Invesco QQQ Trust" },
  { tv: "NASDAQ:QQQM",  label: "QQQM",  group: "ETFs", description: "Invesco NASDAQ 100 ETF" },
  { tv: "NASDAQ:ONEQ",  label: "ONEQ",  group: "ETFs", description: "Fidelity NASDAQ Composite" },
  { tv: "AMEX:DIA",     label: "DIA",   group: "ETFs", description: "SPDR Dow Jones Industrial" },
  { tv: "AMEX:VTI",     label: "VTI",   group: "ETFs", description: "Vanguard Total Stock Market" },
  { tv: "AMEX:ITOT",    label: "ITOT",  group: "ETFs", description: "iShares Core Total US Market" },
  { tv: "AMEX:SCHB",    label: "SCHB",  group: "ETFs", description: "Schwab US Broad Market" },
  { tv: "AMEX:SPTM",    label: "SPTM",  group: "ETFs", description: "SPDR Portfolio Total Stock" },
  { tv: "AMEX:IWM",     label: "IWM",   group: "ETFs", description: "iShares Russell 2000" },
  { tv: "AMEX:VTWO",    label: "VTWO",  group: "ETFs", description: "Vanguard Russell 2000" },
  { tv: "AMEX:IWF",     label: "IWF",   group: "ETFs", description: "iShares Russell 1000 Growth" },
  { tv: "AMEX:IWD",     label: "IWD",   group: "ETFs", description: "iShares Russell 1000 Value" },
  { tv: "AMEX:IWB",     label: "IWB",   group: "ETFs", description: "iShares Russell 1000 Blend" },
  { tv: "AMEX:MDY",     label: "MDY",   group: "ETFs", description: "SPDR S&P MidCap 400" },
  { tv: "AMEX:IJH",     label: "IJH",   group: "ETFs", description: "iShares Core S&P MidCap" },
  { tv: "AMEX:SPMD",    label: "SPMD",  group: "ETFs", description: "SPDR Portfolio Mid Cap" },
  { tv: "AMEX:IJR",     label: "IJR",   group: "ETFs", description: "iShares Core S&P SmallCap" },
  { tv: "AMEX:SPSM",    label: "SPSM",  group: "ETFs", description: "SPDR Portfolio SmallCap" },
  { tv: "AMEX:RSP",     label: "RSP",   group: "ETFs", description: "Invesco S&P 500 Equal Weight" },
  { tv: "AMEX:EWSC",    label: "EWSC",  group: "ETFs", description: "Invesco S&P SmallCap Equal Wt" },
  { tv: "AMEX:VXF",     label: "VXF",   group: "ETFs", description: "Vanguard Extended Market" },
  // ── ETFs — US Sectors (SPDR) ─────────────────────────────────────────────────
  { tv: "AMEX:XLK",     label: "XLK",   group: "ETFs", description: "Technology Select SPDR" },
  { tv: "AMEX:XLF",     label: "XLF",   group: "ETFs", description: "Financial Select SPDR" },
  { tv: "AMEX:XLE",     label: "XLE",   group: "ETFs", description: "Energy Select SPDR" },
  { tv: "AMEX:XLV",     label: "XLV",   group: "ETFs", description: "Health Care Select SPDR" },
  { tv: "AMEX:XLU",     label: "XLU",   group: "ETFs", description: "Utilities Select SPDR" },
  { tv: "AMEX:XLI",     label: "XLI",   group: "ETFs", description: "Industrial Select SPDR" },
  { tv: "AMEX:XLRE",    label: "XLRE",  group: "ETFs", description: "Real Estate Select SPDR" },
  { tv: "AMEX:XLB",     label: "XLB",   group: "ETFs", description: "Materials Select SPDR" },
  { tv: "AMEX:XLC",     label: "XLC",   group: "ETFs", description: "Comm Services Select SPDR" },
  { tv: "AMEX:XLP",     label: "XLP",   group: "ETFs", description: "Consumer Staples Select SPDR" },
  { tv: "AMEX:XLY",     label: "XLY",   group: "ETFs", description: "Consumer Discret. Select SPDR" },
  // ── ETFs — US Sectors (Vanguard) ─────────────────────────────────────────────
  { tv: "AMEX:VGT",     label: "VGT",   group: "ETFs", description: "Vanguard Information Tech." },
  { tv: "AMEX:VFH",     label: "VFH",   group: "ETFs", description: "Vanguard Financials" },
  { tv: "AMEX:VDE",     label: "VDE",   group: "ETFs", description: "Vanguard Energy" },
  { tv: "AMEX:VHT",     label: "VHT",   group: "ETFs", description: "Vanguard Health Care" },
  { tv: "AMEX:VPU",     label: "VPU",   group: "ETFs", description: "Vanguard Utilities" },
  { tv: "AMEX:VIS",     label: "VIS",   group: "ETFs", description: "Vanguard Industrials" },
  { tv: "AMEX:VNQ",     label: "VNQ",   group: "ETFs", description: "Vanguard Real Estate" },
  { tv: "AMEX:VAW",     label: "VAW",   group: "ETFs", description: "Vanguard Materials" },
  { tv: "AMEX:VOX",     label: "VOX",   group: "ETFs", description: "Vanguard Comm Services" },
  { tv: "AMEX:VCR",     label: "VCR",   group: "ETFs", description: "Vanguard Consumer Discret." },
  { tv: "AMEX:VDC",     label: "VDC",   group: "ETFs", description: "Vanguard Consumer Staples" },
  // ── ETFs — US Sub-Sector ─────────────────────────────────────────────────────
  { tv: "NASDAQ:SOXX",  label: "SOXX",  group: "ETFs", description: "iShares Semiconductor" },
  { tv: "AMEX:SMH",     label: "SMH",   group: "ETFs", description: "VanEck Semiconductor" },
  { tv: "NASDAQ:IBB",   label: "IBB",   group: "ETFs", description: "iShares Nasdaq Biotech" },
  { tv: "AMEX:XBI",     label: "XBI",   group: "ETFs", description: "SPDR S&P Biotech" },
  { tv: "AMEX:IGV",     label: "IGV",   group: "ETFs", description: "iShares Expanded Tech-Software" },
  { tv: "AMEX:XOP",     label: "XOP",   group: "ETFs", description: "SPDR S&P Oil & Gas E&P" },
  { tv: "AMEX:FTXN",    label: "FTXN",  group: "ETFs", description: "First Trust Nasdaq Oil & Gas" },
  { tv: "AMEX:KRE",     label: "KRE",   group: "ETFs", description: "SPDR S&P Regional Banking" },
  { tv: "AMEX:IAT",     label: "IAT",   group: "ETFs", description: "iShares US Insurance" },
  { tv: "AMEX:ITB",     label: "ITB",   group: "ETFs", description: "iShares US Home Construction" },
  { tv: "AMEX:XHB",     label: "XHB",   group: "ETFs", description: "SPDR S&P Homebuilders" },
  { tv: "AMEX:JETS",    label: "JETS",  group: "ETFs", description: "US Global JETS Airline" },
  { tv: "AMEX:XRT",     label: "XRT",   group: "ETFs", description: "SPDR S&P Retail" },
  { tv: "AMEX:RETL",    label: "RETL",  group: "ETFs", description: "Direxion Daily Retail 3x" },
  { tv: "AMEX:XME",     label: "XME",   group: "ETFs", description: "SPDR S&P Metals & Mining" },
  { tv: "AMEX:PICK",    label: "PICK",  group: "ETFs", description: "iShares MSCI Global Metals" },
  { tv: "AMEX:MOO",     label: "MOO",   group: "ETFs", description: "VanEck Agribusiness" },
  { tv: "AMEX:FINX",    label: "FINX",  group: "ETFs", description: "Global X FinTech" },
  // ── ETFs — International Developed ───────────────────────────────────────────
  { tv: "AMEX:EFA",     label: "EFA",   group: "ETFs", description: "iShares MSCI EAFE" },
  { tv: "NASDAQ:VEA",   label: "VEA",   group: "ETFs", description: "Vanguard FTSE Dev. Markets" },
  { tv: "AMEX:SPDW",    label: "SPDW",  group: "ETFs", description: "SPDR Portfolio Dev. World ex-US" },
  { tv: "AMEX:IDEV",    label: "IDEV",  group: "ETFs", description: "iShares Core MSCI Intl Dev." },
  { tv: "AMEX:EWJ",     label: "EWJ",   group: "ETFs", description: "iShares MSCI Japan" },
  { tv: "AMEX:DXJ",     label: "DXJ",   group: "ETFs", description: "WisdomTree Japan Hedged Equity" },
  { tv: "AMEX:EWG",     label: "EWG",   group: "ETFs", description: "iShares MSCI Germany" },
  { tv: "AMEX:HEWG",    label: "HEWG",  group: "ETFs", description: "iShares Currency-Hedged Germany" },
  { tv: "AMEX:EWU",     label: "EWU",   group: "ETFs", description: "iShares MSCI United Kingdom" },
  { tv: "AMEX:EWC",     label: "EWC",   group: "ETFs", description: "iShares MSCI Canada" },
  { tv: "AMEX:EWA",     label: "EWA",   group: "ETFs", description: "iShares MSCI Australia" },
  { tv: "AMEX:EWL",     label: "EWL",   group: "ETFs", description: "iShares MSCI Switzerland" },
  { tv: "AMEX:EWQ",     label: "EWQ",   group: "ETFs", description: "iShares MSCI France" },
  { tv: "AMEX:EWD",     label: "EWD",   group: "ETFs", description: "iShares MSCI Sweden" },
  { tv: "AMEX:EWN",     label: "EWN",   group: "ETFs", description: "iShares MSCI Netherlands" },
  { tv: "AMEX:EWP",     label: "EWP",   group: "ETFs", description: "iShares MSCI Spain" },
  { tv: "AMEX:EWI",     label: "EWI",   group: "ETFs", description: "iShares MSCI Italy" },
  // ── ETFs — International Emerging ────────────────────────────────────────────
  { tv: "AMEX:EEM",     label: "EEM",   group: "ETFs", description: "iShares MSCI Emerging Markets" },
  { tv: "AMEX:VWO",     label: "VWO",   group: "ETFs", description: "Vanguard FTSE Emerging Markets" },
  { tv: "AMEX:SPEM",    label: "SPEM",  group: "ETFs", description: "SPDR Portfolio Emerging Markets" },
  { tv: "AMEX:IEMG",    label: "IEMG",  group: "ETFs", description: "iShares Core MSCI Emerging Mkt" },
  { tv: "AMEX:FXI",     label: "FXI",   group: "ETFs", description: "iShares China Large-Cap" },
  { tv: "AMEX:MCHI",    label: "MCHI",  group: "ETFs", description: "iShares MSCI China" },
  { tv: "AMEX:KWEB",    label: "KWEB",  group: "ETFs", description: "KraneShares China Internet" },
  { tv: "AMEX:INDA",    label: "INDA",  group: "ETFs", description: "iShares MSCI India" },
  { tv: "AMEX:SMIN",    label: "SMIN",  group: "ETFs", description: "iShares MSCI India Small-Cap" },
  { tv: "AMEX:EWZ",     label: "EWZ",   group: "ETFs", description: "iShares MSCI Brazil" },
  { tv: "AMEX:EWT",     label: "EWT",   group: "ETFs", description: "iShares MSCI Taiwan" },
  { tv: "AMEX:EWY",     label: "EWY",   group: "ETFs", description: "iShares MSCI South Korea" },
  { tv: "AMEX:EWH",     label: "EWH",   group: "ETFs", description: "iShares MSCI Hong Kong" },
  { tv: "AMEX:EWS",     label: "EWS",   group: "ETFs", description: "iShares MSCI Singapore" },
  { tv: "AMEX:EWM",     label: "EWM",   group: "ETFs", description: "iShares MSCI Malaysia" },
  { tv: "AMEX:EWW",     label: "EWW",   group: "ETFs", description: "iShares MSCI Mexico" },
  { tv: "AMEX:ECH",     label: "ECH",   group: "ETFs", description: "iShares MSCI Chile" },
  { tv: "AMEX:EPOL",    label: "EPOL",  group: "ETFs", description: "iShares MSCI Poland" },
  // ── ETFs — Fixed Income Government ───────────────────────────────────────────
  { tv: "NASDAQ:TLT",   label: "TLT",   group: "ETFs", description: "iShares 20+ Yr Treasury" },
  { tv: "AMEX:VGLT",    label: "VGLT",  group: "ETFs", description: "Vanguard Long-Term Treasury" },
  { tv: "AMEX:EDV",     label: "EDV",   group: "ETFs", description: "Vanguard Extended Duration" },
  { tv: "AMEX:ZROZ",    label: "ZROZ",  group: "ETFs", description: "PIMCO 25+ Yr Zero Coupon" },
  { tv: "NASDAQ:IEF",   label: "IEF",   group: "ETFs", description: "iShares 7-10 Yr Treasury" },
  { tv: "AMEX:VGIT",    label: "VGIT",  group: "ETFs", description: "Vanguard Intermediate Treasury" },
  { tv: "NASDAQ:IEI",   label: "IEI",   group: "ETFs", description: "iShares 3-7 Yr Treasury" },
  { tv: "NASDAQ:SHY",   label: "SHY",   group: "ETFs", description: "iShares 1-3 Yr Treasury" },
  { tv: "AMEX:VGSH",    label: "VGSH",  group: "ETFs", description: "Vanguard Short-Term Treasury" },
  { tv: "AMEX:BIL",     label: "BIL",   group: "ETFs", description: "SPDR 1-3 Month T-Bill" },
  { tv: "AMEX:SGOV",    label: "SGOV",  group: "ETFs", description: "iShares 0-3 Month T-Bill" },
  { tv: "AMEX:TBT",     label: "TBT",   group: "ETFs", description: "ProShares UltraShort 20+ Yr" },
  { tv: "AMEX:TBF",     label: "TBF",   group: "ETFs", description: "ProShares Short 20+ Yr Treasury" },
  // ── ETFs — Fixed Income Aggregate & Credit ────────────────────────────────────
  { tv: "NASDAQ:AGG",   label: "AGG",   group: "ETFs", description: "iShares Core US Agg Bond" },
  { tv: "NASDAQ:BND",   label: "BND",   group: "ETFs", description: "Vanguard Total Bond Market" },
  { tv: "NASDAQ:BNDX",  label: "BNDX",  group: "ETFs", description: "Vanguard Total International Bond" },
  { tv: "AMEX:BSV",     label: "BSV",   group: "ETFs", description: "Vanguard Short-Term Bond" },
  { tv: "AMEX:BIV",     label: "BIV",   group: "ETFs", description: "Vanguard Intermediate-Term Bond" },
  { tv: "AMEX:BLV",     label: "BLV",   group: "ETFs", description: "Vanguard Long-Term Bond" },
  { tv: "NASDAQ:LQD",   label: "LQD",   group: "ETFs", description: "iShares IG Corporate Bond" },
  { tv: "AMEX:VCLT",    label: "VCLT",  group: "ETFs", description: "Vanguard Long-Term Corp. Bond" },
  { tv: "NASDAQ:IGIB",  label: "IGIB",  group: "ETFs", description: "iShares Intermediate Corp. Bond" },
  { tv: "NASDAQ:HYG",   label: "HYG",   group: "ETFs", description: "iShares HY Corporate Bond" },
  { tv: "AMEX:JNK",     label: "JNK",   group: "ETFs", description: "SPDR Bloomberg High Yield" },
  { tv: "AMEX:USHY",    label: "USHY",  group: "ETFs", description: "iShares Broad USD High Yield" },
  { tv: "AMEX:BKLN",    label: "BKLN",  group: "ETFs", description: "Invesco Senior Loan" },
  { tv: "AMEX:SRLN",    label: "SRLN",  group: "ETFs", description: "SPDR Blackstone Sr. Loan" },
  { tv: "NASDAQ:EMB",   label: "EMB",   group: "ETFs", description: "iShares JP Morgan EM Bond" },
  { tv: "AMEX:PCY",     label: "PCY",   group: "ETFs", description: "Invesco Emerging Markets Bond" },
  { tv: "AMEX:VWOB",    label: "VWOB",  group: "ETFs", description: "Vanguard Emerging Markets Govt" },
  // ── ETFs — Fixed Income Inflation & Muni ────────────────────────────────────
  { tv: "NASDAQ:TIP",   label: "TIP",   group: "ETFs", description: "iShares TIPS Bond" },
  { tv: "NASDAQ:VTIP",  label: "VTIP",  group: "ETFs", description: "Vanguard Short-Term TIPS" },
  { tv: "AMEX:SCHP",    label: "SCHP",  group: "ETFs", description: "Schwab US TIPS ETF" },
  { tv: "AMEX:STIP",    label: "STIP",  group: "ETFs", description: "iShares 0-5 Yr TIPS" },
  { tv: "AMEX:MUB",     label: "MUB",   group: "ETFs", description: "iShares National Muni Bond" },
  { tv: "AMEX:VTEB",    label: "VTEB",  group: "ETFs", description: "Vanguard Tax-Exempt Bond" },
  { tv: "AMEX:HYD",     label: "HYD",   group: "ETFs", description: "VanEck High Yield Muni" },
  // ── ETFs — Commodities Precious Metals ───────────────────────────────────────
  { tv: "AMEX:GLD",     label: "GLD",   group: "ETFs", description: "SPDR Gold Shares" },
  { tv: "AMEX:IAU",     label: "IAU",   group: "ETFs", description: "iShares Gold Trust" },
  { tv: "AMEX:GLDM",    label: "GLDM",  group: "ETFs", description: "SPDR Gold MiniShares" },
  { tv: "AMEX:SGOL",    label: "SGOL",  group: "ETFs", description: "Aberdeen Physical Gold" },
  { tv: "AMEX:OUNZ",    label: "OUNZ",  group: "ETFs", description: "VanEck Merk Gold Trust" },
  { tv: "AMEX:SLV",     label: "SLV",   group: "ETFs", description: "iShares Silver Trust" },
  { tv: "AMEX:SIVR",    label: "SIVR",  group: "ETFs", description: "Aberdeen Physical Silver" },
  { tv: "AMEX:PPLT",    label: "PPLT",  group: "ETFs", description: "Aberdeen Physical Platinum" },
  // ── ETFs — Commodities Energy ─────────────────────────────────────────────────
  { tv: "AMEX:USO",     label: "USO",   group: "ETFs", description: "United States Oil Fund" },
  { tv: "AMEX:DBO",     label: "DBO",   group: "ETFs", description: "Invesco DB Oil Fund" },
  { tv: "AMEX:OILK",    label: "OILK",  group: "ETFs", description: "ProShares K-1 Free Crude Oil" },
  { tv: "AMEX:UNG",     label: "UNG",   group: "ETFs", description: "United States Natural Gas" },
  { tv: "AMEX:BOIL",    label: "BOIL",  group: "ETFs", description: "ProShares Ultra Bloomberg Nat Gas" },
  { tv: "AMEX:KOLD",    label: "KOLD",  group: "ETFs", description: "ProShares UltraShort Nat Gas" },
  // ── ETFs — Commodities Broad ─────────────────────────────────────────────────
  { tv: "AMEX:PDBC",    label: "PDBC",  group: "ETFs", description: "Invesco Optimum Yield Cmdty" },
  { tv: "AMEX:DJP",     label: "DJP",   group: "ETFs", description: "iPath Bloomberg Cmdty Total" },
  { tv: "AMEX:GSG",     label: "GSG",   group: "ETFs", description: "iShares S&P GSCI Cmdty" },
  { tv: "AMEX:COMB",    label: "COMB",  group: "ETFs", description: "GraniteShares Bloomberg Cmdty" },
  { tv: "AMEX:COMT",    label: "COMT",  group: "ETFs", description: "iShares GSCI Cmdty Dyn Roll" },
  { tv: "AMEX:CPER",    label: "CPER",  group: "ETFs", description: "United States Copper Index" },
  { tv: "AMEX:DBA",     label: "DBA",   group: "ETFs", description: "Invesco DB Agriculture Fund" },
  { tv: "AMEX:CORN",    label: "CORN",  group: "ETFs", description: "Teucrium Corn Fund" },
  { tv: "AMEX:WEAT",    label: "WEAT",  group: "ETFs", description: "Teucrium Wheat Fund" },
  { tv: "AMEX:SOYB",    label: "SOYB",  group: "ETFs", description: "Teucrium Soybean Fund" },
  { tv: "AMEX:URA",     label: "URA",   group: "ETFs", description: "Global X Uranium ETF" },
  { tv: "AMEX:URNM",    label: "URNM",  group: "ETFs", description: "Sprott Uranium Miners" },
  // ── ETFs — Dividend & Income ─────────────────────────────────────────────────
  { tv: "AMEX:SCHD",    label: "SCHD",  group: "ETFs", description: "Schwab US Dividend Equity" },
  { tv: "AMEX:VIG",     label: "VIG",   group: "ETFs", description: "Vanguard Dividend Appreciation" },
  { tv: "AMEX:VYM",     label: "VYM",   group: "ETFs", description: "Vanguard High Dividend Yield" },
  { tv: "AMEX:HDV",     label: "HDV",   group: "ETFs", description: "iShares Core High Dividend" },
  { tv: "AMEX:DVY",     label: "DVY",   group: "ETFs", description: "iShares Select Dividend" },
  { tv: "AMEX:DGRO",    label: "DGRO",  group: "ETFs", description: "iShares Core Dividend Growth" },
  { tv: "AMEX:SPHD",    label: "SPHD",  group: "ETFs", description: "Invesco S&P 500 High Div Low Vol" },
  { tv: "AMEX:SPYD",    label: "SPYD",  group: "ETFs", description: "SPDR S&P 500 High Dividend" },
  { tv: "AMEX:NOBL",    label: "NOBL",  group: "ETFs", description: "ProShares S&P 500 Div Aristocrats" },
  { tv: "AMEX:REGL",    label: "REGL",  group: "ETFs", description: "ProShares S&P MidCap Div Aristoc." },
  { tv: "AMEX:WDIV",    label: "WDIV",  group: "ETFs", description: "SPDR S&P Global Dividend" },
  // ── ETFs — Factor / Smart Beta ───────────────────────────────────────────────
  { tv: "AMEX:MTUM",    label: "MTUM",  group: "ETFs", description: "iShares MSCI USA Momentum" },
  { tv: "AMEX:QMOM",    label: "QMOM",  group: "ETFs", description: "Alpha Architect US Quant Momentum" },
  { tv: "AMEX:VLUE",    label: "VLUE",  group: "ETFs", description: "iShares MSCI USA Value" },
  { tv: "AMEX:RPV",     label: "RPV",   group: "ETFs", description: "Invesco S&P 500 Pure Value" },
  { tv: "AMEX:QUAL",    label: "QUAL",  group: "ETFs", description: "iShares MSCI USA Quality" },
  { tv: "AMEX:DGRW",    label: "DGRW",  group: "ETFs", description: "WisdomTree US Qual Div Growth" },
  { tv: "AMEX:USMV",    label: "USMV",  group: "ETFs", description: "iShares MSCI USA Min Volatility" },
  { tv: "AMEX:SPLV",    label: "SPLV",  group: "ETFs", description: "Invesco S&P 500 Low Volatility" },
  { tv: "AMEX:EFAV",    label: "EFAV",  group: "ETFs", description: "iShares MSCI EAFE Min Volatility" },
  { tv: "AMEX:COWZ",    label: "COWZ",  group: "ETFs", description: "Pacer US Cash Cows 100" },
  { tv: "AMEX:CALF",    label: "CALF",  group: "ETFs", description: "Pacer US Small Cap Cash Cows 100" },
  // ── ETFs — Volatility ────────────────────────────────────────────────────────
  { tv: "AMEX:UVXY",    label: "UVXY",  group: "ETFs", description: "ProShares Ultra VIX Short-Term" },
  { tv: "AMEX:VIXY",    label: "VIXY",  group: "ETFs", description: "ProShares VIX Short-Term Futures" },
  { tv: "AMEX:VXX",     label: "VXX",   group: "ETFs", description: "iPath Series B VIX ST Futures" },
  { tv: "AMEX:SVXY",    label: "SVXY",  group: "ETFs", description: "ProShares Short VIX Short-Term" },
  { tv: "AMEX:VIXM",    label: "VIXM",  group: "ETFs", description: "ProShares VIX Mid-Term Futures" },
  // ── ETFs — Leveraged Long ─────────────────────────────────────────────────────
  { tv: "AMEX:SSO",     label: "SSO",   group: "ETFs", description: "ProShares Ultra S&P 500 (2x)" },
  { tv: "AMEX:SPXL",    label: "SPXL",  group: "ETFs", description: "Direxion Daily S&P 500 Bull 3x" },
  { tv: "AMEX:UPRO",    label: "UPRO",  group: "ETFs", description: "ProShares UltraPro S&P 500 (3x)" },
  { tv: "AMEX:QLD",     label: "QLD",   group: "ETFs", description: "ProShares Ultra QQQ (2x)" },
  { tv: "NASDAQ:TQQQ",  label: "TQQQ",  group: "ETFs", description: "ProShares UltraPro QQQ (3x)" },
  { tv: "AMEX:TNA",     label: "TNA",   group: "ETFs", description: "Direxion Daily R2k Bull 3x" },
  { tv: "AMEX:URTY",    label: "URTY",  group: "ETFs", description: "ProShares UltraPro Russell2k (3x)" },
  { tv: "AMEX:TMF",     label: "TMF",   group: "ETFs", description: "Direxion Daily 20Yr+ Bull 3x" },
  { tv: "AMEX:UBT",     label: "UBT",   group: "ETFs", description: "ProShares Ultra 20+ Yr Treasury" },
  { tv: "AMEX:LABU",    label: "LABU",  group: "ETFs", description: "Direxion Daily S&P Biotech Bull 3x" },
  { tv: "AMEX:SOXL",    label: "SOXL",  group: "ETFs", description: "Direxion Daily Semi Bull 3x" },
  { tv: "AMEX:FAS",     label: "FAS",   group: "ETFs", description: "Direxion Daily Financials Bull 3x" },
  // ── ETFs — Leveraged Inverse ─────────────────────────────────────────────────
  { tv: "AMEX:SDS",     label: "SDS",   group: "ETFs", description: "ProShares UltraShort S&P 500 (2x)" },
  { tv: "AMEX:SPXU",    label: "SPXU",  group: "ETFs", description: "ProShares UltraPro Short S&P (3x)" },
  { tv: "AMEX:SPXS",    label: "SPXS",  group: "ETFs", description: "Direxion Daily S&P Bear 3x" },
  { tv: "AMEX:QID",     label: "QID",   group: "ETFs", description: "ProShares UltraShort QQQ (2x)" },
  { tv: "NASDAQ:SQQQ",  label: "SQQQ",  group: "ETFs", description: "ProShares UltraPro Short QQQ (3x)" },
  { tv: "AMEX:TZA",     label: "TZA",   group: "ETFs", description: "Direxion Daily R2k Bear 3x" },
  { tv: "AMEX:SRTY",    label: "SRTY",  group: "ETFs", description: "ProShares UltraPro Short Russell (3x)" },
  { tv: "AMEX:PFIX",    label: "PFIX",  group: "ETFs", description: "Simplify Interest Rate Hedge" },
  { tv: "AMEX:LABD",    label: "LABD",  group: "ETFs", description: "Direxion Daily S&P Biotech Bear 3x" },
  { tv: "AMEX:SOXS",    label: "SOXS",  group: "ETFs", description: "Direxion Daily Semi Bear 3x" },
  { tv: "AMEX:FAZ",     label: "FAZ",   group: "ETFs", description: "Direxion Daily Financials Bear 3x" },
  { tv: "AMEX:DUST",    label: "DUST",  group: "ETFs", description: "Direxion Daily Gold Miners Bear 3x" },
  { tv: "AMEX:JDST",    label: "JDST",  group: "ETFs", description: "Direxion Daily Jr Gold Miners Bear 3x" },
  // ── ETFs — Crypto ────────────────────────────────────────────────────────────
  { tv: "NASDAQ:IBIT",  label: "IBIT",  group: "ETFs", description: "iShares Bitcoin Trust" },
  { tv: "AMEX:FBTC",    label: "FBTC",  group: "ETFs", description: "Fidelity Wise Origin Bitcoin" },
  { tv: "AMEX:BITB",    label: "BITB",  group: "ETFs", description: "Bitwise Bitcoin ETF" },
  { tv: "AMEX:ARKB",    label: "ARKB",  group: "ETFs", description: "ARK 21Shares Bitcoin ETF" },
  { tv: "AMEX:HODL",    label: "HODL",  group: "ETFs", description: "VanEck Bitcoin Trust" },
  { tv: "AMEX:BTCO",    label: "BTCO",  group: "ETFs", description: "Invesco Galaxy Bitcoin ETF" },
  { tv: "AMEX:GBTC",    label: "GBTC",  group: "ETFs", description: "Grayscale Bitcoin Trust" },
  { tv: "AMEX:ETHE",    label: "ETHE",  group: "ETFs", description: "Grayscale Ethereum Trust" },
  { tv: "AMEX:BITO",    label: "BITO",  group: "ETFs", description: "ProShares Bitcoin Strategy" },
  { tv: "AMEX:BTF",     label: "BTF",   group: "ETFs", description: "Valkyrie Bitcoin Futures" },
  { tv: "CBOE:XBTF",    label: "XBTF",  group: "ETFs", description: "VanEck Bitcoin Futures" },
  { tv: "NASDAQ:BITX",  label: "BITX",  group: "ETFs", description: "2x Bitcoin Strategy ETF" },
  { tv: "AMEX:BITU",    label: "BITU",  group: "ETFs", description: "ProShares Ultra Bitcoin (2x)" },
  { tv: "AMEX:ETHU",    label: "ETHU",  group: "ETFs", description: "ProShares Ultra Ether (2x)" },
  // ── ETFs — Thematic ──────────────────────────────────────────────────────────
  { tv: "AMEX:ARKK",    label: "ARKK",  group: "ETFs", description: "ARK Innovation ETF" },
  { tv: "AMEX:ARKG",    label: "ARKG",  group: "ETFs", description: "ARK Genomic Revolution" },
  { tv: "AMEX:ARKQ",    label: "ARKQ",  group: "ETFs", description: "ARK Autonomous Tech & Robotics" },
  { tv: "AMEX:ARKF",    label: "ARKF",  group: "ETFs", description: "ARK Fintech Innovation" },
  { tv: "AMEX:ARKW",    label: "ARKW",  group: "ETFs", description: "ARK Next Generation Internet" },
  { tv: "AMEX:ARKVX",   label: "ARKVX", group: "ETFs", description: "ARK Venture Fund" },
  { tv: "AMEX:ICLN",    label: "ICLN",  group: "ETFs", description: "iShares Global Clean Energy" },
  { tv: "AMEX:FAN",     label: "FAN",   group: "ETFs", description: "First Trust Global Wind Energy" },
  { tv: "NASDAQ:QCLN",  label: "QCLN",  group: "ETFs", description: "First Trust NASDAQ Clean Edge" },
  { tv: "AMEX:ACES",    label: "ACES",  group: "ETFs", description: "ALPS Clean Energy ETF" },
  { tv: "AMEX:LIT",     label: "LIT",   group: "ETFs", description: "Global X Lithium & Battery Tech" },
  { tv: "AMEX:BATT",    label: "BATT",  group: "ETFs", description: "Amplify Lithium & Battery Tech" },
  { tv: "AMEX:DRIV",    label: "DRIV",  group: "ETFs", description: "Global X Autonomous & EV" },
  { tv: "NASDAQ:BOTZ",  label: "BOTZ",  group: "ETFs", description: "Global X Robotics & AI" },
  { tv: "NASDAQ:ROBO",  label: "ROBO",  group: "ETFs", description: "ROBO Global Robotics" },
  { tv: "NYSE:AIQ",     label: "AIQ",   group: "ETFs", description: "Global X AI & Technology" },
  { tv: "AMEX:CHAT",    label: "CHAT",  group: "ETFs", description: "Roundhill Generative AI & Tech" },
  { tv: "NASDAQ:CIBR",  label: "CIBR",  group: "ETFs", description: "First Trust NASDAQ Cybersecurity" },
  { tv: "NASDAQ:HACK",  label: "HACK",  group: "ETFs", description: "ETFMG Cybersecurity" },
  { tv: "AMEX:BUG",     label: "BUG",   group: "ETFs", description: "Global X Cybersecurity" },
  { tv: "AMEX:UFO",     label: "UFO",   group: "ETFs", description: "Procure Space ETF" },
  { tv: "AMEX:ROKT",    label: "ROKT",  group: "ETFs", description: "SPDR S&P Kensho Final Frontiers" },
  { tv: "AMEX:BLOK",    label: "BLOK",  group: "ETFs", description: "Amplify Transformational Data Shr" },
  { tv: "AMEX:LEGR",    label: "LEGR",  group: "ETFs", description: "First Trust Indxx Innovative Trans." },
  { tv: "AMEX:PAVE",    label: "PAVE",  group: "ETFs", description: "Global X US Infrastructure Dev." },
  { tv: "AMEX:IFRA",    label: "IFRA",  group: "ETFs", description: "iShares US Infrastructure" },
  { tv: "AMEX:NFRA",    label: "NFRA",  group: "ETFs", description: "FlexShares STOXX Global Broad Infra" },
  { tv: "AMEX:HERO",    label: "HERO",  group: "ETFs", description: "Global X Video Games & Esports" },
  { tv: "AMEX:ESPO",    label: "ESPO",  group: "ETFs", description: "VanEck Video Gaming and eSports" },
  { tv: "AMEX:NERD",    label: "NERD",  group: "ETFs", description: "Roundhill BITKRAFT Esports" },
  { tv: "AMEX:MSOS",    label: "MSOS",  group: "ETFs", description: "AdvisorShares Pure US Cannabis" },
  { tv: "AMEX:MJ",      label: "MJ",    group: "ETFs", description: "ETFMG Alternative Harvest" },
  { tv: "AMEX:AWAY",    label: "AWAY",  group: "ETFs", description: "ETFMG Travel Tech ETF" },
  { tv: "AMEX:GAMR",    label: "GAMR",  group: "ETFs", description: "ETFMG Video Game Tech" },

  // ── Crypto ────────────────────────────────────────────────────────────────────
  { tv: "BINANCE:BTCUSDT",   label: "BTC/USDT",   group: "Crypto", description: "Bitcoin / Tether" },
  { tv: "BINANCE:ETHUSDT",   label: "ETH/USDT",   group: "Crypto", description: "Ethereum / Tether" },
  { tv: "BINANCE:SOLUSDT",   label: "SOL/USDT",   group: "Crypto", description: "Solana / Tether" },
  { tv: "BINANCE:BNBUSDT",   label: "BNB/USDT",   group: "Crypto", description: "BNB / Tether" },
  { tv: "BINANCE:XRPUSDT",   label: "XRP/USDT",   group: "Crypto", description: "XRP / Tether" },
  { tv: "BINANCE:ADAUSDT",   label: "ADA/USDT",   group: "Crypto", description: "Cardano / Tether" },
  { tv: "BINANCE:DOGEUSDT",  label: "DOGE/USDT",  group: "Crypto", description: "Dogecoin / Tether" },
  { tv: "BINANCE:AVAXUSDT",  label: "AVAX/USDT",  group: "Crypto", description: "Avalanche / Tether" },
  { tv: "BINANCE:LINKUSDT",  label: "LINK/USDT",  group: "Crypto", description: "Chainlink / Tether" },
  { tv: "BINANCE:DOTUSDT",   label: "DOT/USDT",   group: "Crypto", description: "Polkadot / Tether" },
  { tv: "BINANCE:MATICUSDT", label: "MATIC/USDT", group: "Crypto", description: "Polygon / Tether" },
  { tv: "BINANCE:LTCUSDT",   label: "LTC/USDT",   group: "Crypto", description: "Litecoin / Tether" },
  { tv: "BINANCE:UNIUSDT",   label: "UNI/USDT",   group: "Crypto", description: "Uniswap / Tether" },
  { tv: "BINANCE:AAVEUSDT",  label: "AAVE/USDT",  group: "Crypto", description: "Aave / Tether" },
  { tv: "BINANCE:ATOMUSDT",  label: "ATOM/USDT",  group: "Crypto", description: "Cosmos / Tether" },
  { tv: "BINANCE:NEARUSDT",  label: "NEAR/USDT",  group: "Crypto", description: "NEAR Protocol / Tether" },
  { tv: "BINANCE:APTUSDT",   label: "APT/USDT",   group: "Crypto", description: "Aptos / Tether" },
  { tv: "BINANCE:SUIUSDT",   label: "SUI/USDT",   group: "Crypto", description: "Sui / Tether" },

  // ── Forex — Majors ────────────────────────────────────────────────────────────
  { tv: "FX:EURUSD", label: "EUR/USD", group: "Forex", description: "Euro / US Dollar" },
  { tv: "FX:GBPUSD", label: "GBP/USD", group: "Forex", description: "British Pound / US Dollar" },
  { tv: "FX:USDJPY", label: "USD/JPY", group: "Forex", description: "US Dollar / Japanese Yen" },
  { tv: "FX:AUDUSD", label: "AUD/USD", group: "Forex", description: "Australian Dollar / US Dollar" },
  { tv: "FX:USDCHF", label: "USD/CHF", group: "Forex", description: "US Dollar / Swiss Franc" },
  { tv: "FX:USDCAD", label: "USD/CAD", group: "Forex", description: "US Dollar / Canadian Dollar" },
  { tv: "FX:NZDUSD", label: "NZD/USD", group: "Forex", description: "New Zealand Dollar / US Dollar" },
  // ── Forex — Crosses ───────────────────────────────────────────────────────────
  { tv: "FX:EURGBP", label: "EUR/GBP", group: "Forex", description: "Euro / British Pound" },
  { tv: "FX:EURJPY", label: "EUR/JPY", group: "Forex", description: "Euro / Japanese Yen" },
  { tv: "FX:GBPJPY", label: "GBP/JPY", group: "Forex", description: "British Pound / Japanese Yen" },
  { tv: "FX:AUDJPY", label: "AUD/JPY", group: "Forex", description: "Australian Dollar / Yen" },
  { tv: "FX:EURCHF", label: "EUR/CHF", group: "Forex", description: "Euro / Swiss Franc" },
  { tv: "FX:GBPCHF", label: "GBP/CHF", group: "Forex", description: "British Pound / Swiss Franc" },
  { tv: "FX:EURCAD", label: "EUR/CAD", group: "Forex", description: "Euro / Canadian Dollar" },
  { tv: "FX:CADJPY", label: "CAD/JPY", group: "Forex", description: "Canadian Dollar / Yen" },
  { tv: "FX:AUDNZD", label: "AUD/NZD", group: "Forex", description: "AUD / New Zealand Dollar" },
  { tv: "FX:NZDJPY", label: "NZD/JPY", group: "Forex", description: "New Zealand Dollar / Yen" },
  // ── Forex — Metals ────────────────────────────────────────────────────────────
  { tv: "TVC:GOLD",   label: "XAU/USD", group: "Forex", description: "Gold / US Dollar" },
  { tv: "TVC:SILVER", label: "XAG/USD", group: "Forex", description: "Silver / US Dollar" },
  { tv: "TVC:PLATINUM", label: "XPT/USD", group: "Forex", description: "Platinum / US Dollar" },

  // ── Market Indices ────────────────────────────────────────────────────────────
  // US Broad
  { tv: "TVC:SPX",    label: "S&P 500",    group: "Indices", description: "S&P 500 — 500 largest US companies" },
  { tv: "TVC:NDX",    label: "NASDAQ 100", group: "Indices", description: "NASDAQ 100 — top 100 non-financial NASDAQ companies" },
  { tv: "TVC:DJI",    label: "Dow Jones",  group: "Indices", description: "DJIA — 30 large US blue-chip companies" },
  { tv: "TVC:RUT",    label: "Russell 2000", group: "Indices", description: "Russell 2000 — 2000 small-cap US companies" },
  { tv: "TVC:WILLR",  label: "Wilshire 5000", group: "Indices", description: "Wilshire 5000 — total US stock market" },
  // Volatility & Fear
  { tv: "CBOE:VIX",   label: "VIX",        group: "Indices", description: "CBOE Volatility Index — 30-day S&P 500 implied volatility" },
  { tv: "CBOE:VXN",   label: "VXN",        group: "Indices", description: "NASDAQ Volatility Index — NASDAQ 100 implied volatility" },
  { tv: "CBOE:VVIX",  label: "VVIX",       group: "Indices", description: "VIX of VIX — volatility of volatility index" },
  // Macro / Rates
  { tv: "TVC:US10Y",  label: "US 10Y",     group: "Indices", description: "10-Year US Treasury Yield" },
  { tv: "TVC:US02Y",  label: "US 2Y",      group: "Indices", description: "2-Year US Treasury Yield" },
  { tv: "TVC:US30Y",  label: "US 30Y",     group: "Indices", description: "30-Year US Treasury Yield" },
  { tv: "TVC:DXY",    label: "DXY",        group: "Indices", description: "US Dollar Index — USD vs basket of 6 currencies" },
  { tv: "TVC:SPREAD", label: "Yield Spread", group: "Indices", description: "10Y-2Y Treasury yield spread" },
  // International
  { tv: "TVC:UKX",    label: "FTSE 100",   group: "Indices", description: "UK FTSE 100 — top 100 London-listed companies" },
  { tv: "TVC:DAX",    label: "DAX 40",     group: "Indices", description: "German DAX — top 40 Frankfurt-listed companies" },
  { tv: "TVC:NI225",  label: "Nikkei 225", group: "Indices", description: "Japan Nikkei 225 — major Tokyo Stock Exchange index" },
  { tv: "TVC:HSI",    label: "Hang Seng",  group: "Indices", description: "Hong Kong Hang Seng Index" },
  { tv: "TVC:CAC40",  label: "CAC 40",     group: "Indices", description: "French CAC 40 — top 40 Euronext Paris companies" },
  { tv: "TVC:SX5E",   label: "Euro Stoxx 50", group: "Indices", description: "Eurozone top 50 blue-chip companies" },
  { tv: "TVC:ASX200", label: "ASX 200",    group: "Indices", description: "Australian ASX 200 — top 200 ASX-listed companies" },
  { tv: "TVC:SENSEX", label: "BSE Sensex", group: "Indices", description: "Indian BSE Sensex — 30 large Bombay-listed companies" },
  // Sectors (US) — represented by ETF charts on TradingView
  { tv: "AMEX:XLK",   label: "Tech Sector",   group: "Indices", description: "S&P 500 Technology sector (XLK)" },
  { tv: "AMEX:XLF",   label: "Financials",    group: "Indices", description: "S&P 500 Financials sector (XLF)" },
  { tv: "AMEX:XLV",   label: "Healthcare",    group: "Indices", description: "S&P 500 Healthcare sector (XLV)" },
  { tv: "AMEX:XLE",   label: "Energy Sector", group: "Indices", description: "S&P 500 Energy sector (XLE)" },
  { tv: "AMEX:XLI",   label: "Industrials",   group: "Indices", description: "S&P 500 Industrials sector (XLI)" },
  { tv: "AMEX:XLRE",  label: "Real Estate",   group: "Indices", description: "S&P 500 Real Estate sector (XLRE)" },
  // Commodities
  { tv: "TVC:GOLD",   label: "Gold",       group: "Indices", description: "Gold spot price (XAU/USD)" },
  { tv: "TVC:SILVER", label: "Silver",     group: "Indices", description: "Silver spot price (XAG/USD)" },
  { tv: "NYMEX:CL1!", label: "Crude Oil",  group: "Indices", description: "WTI Crude Oil front-month futures" },
  { tv: "NYMEX:NG1!", label: "Nat. Gas",   group: "Indices", description: "Henry Hub Natural Gas front-month futures" },
  { tv: "TVC:BCOM",   label: "Bloomberg Cmdty", group: "Indices", description: "Bloomberg Commodity Index — diversified basket" },

  // ── NGX — Nigerian Exchange ───────────────────────────────────────────────────
  { tv: "NGXGROUP:DANGCEM",    label: "DANGCEM",    group: "NGX", description: "Dangote Cement" },
  { tv: "NGXGROUP:AIRTELAFRI", label: "AIRTELAFRI", group: "NGX", description: "Airtel Africa" },
  { tv: "NGXGROUP:MTNN",       label: "MTNN",       group: "NGX", description: "MTN Nigeria" },
  { tv: "NGXGROUP:BUAFOODS",   label: "BUAFOODS",   group: "NGX", description: "BUA Foods" },
  { tv: "NGXGROUP:SEPLAT",     label: "SEPLAT",     group: "NGX", description: "Seplat Energy" },
  { tv: "NGXGROUP:BUACEMENT",  label: "BUACEMENT",  group: "NGX", description: "BUA Cement" },
  { tv: "NGXGROUP:GTCO",       label: "GTCO",       group: "NGX", description: "Guaranty Trust Holding Co." },
  { tv: "NGXGROUP:ZENITHBANK", label: "ZENITHBANK", group: "NGX", description: "Zenith Bank" },
  { tv: "NGXGROUP:ACCESSCORP", label: "ACCESSCORP", group: "NGX", description: "Access Holdings" },
  { tv: "NGXGROUP:UBA",        label: "UBA",        group: "NGX", description: "United Bank for Africa" },
  { tv: "NGXGROUP:STANBIC",    label: "STANBIC",    group: "NGX", description: "Stanbic IBTC Holdings" },
  { tv: "NGXGROUP:FBNH",       label: "FBNH",       group: "NGX", description: "FBN Holdings" },
  { tv: "NGXGROUP:FIDELITYBK", label: "FIDELITYBK", group: "NGX", description: "Fidelity Bank" },
  { tv: "NGXGROUP:FCMB",       label: "FCMB",       group: "NGX", description: "FCMB Group" },
  { tv: "NGXGROUP:STERLING",   label: "STERLING",   group: "NGX", description: "Sterling Financial Holdings" },
  { tv: "NGXGROUP:WEMABANK",   label: "WEMABANK",   group: "NGX", description: "Wema Bank" },
  { tv: "NGXGROUP:UNIONBANK",  label: "UNIONBANK",  group: "NGX", description: "Union Bank of Nigeria" },
  { tv: "NGXGROUP:JAIZBANK",   label: "JAIZBANK",   group: "NGX", description: "Jaiz Bank" },
  { tv: "NGXGROUP:TRANSCORP",  label: "TRANSCORP",  group: "NGX", description: "Transnational Corp." },
  { tv: "NGXGROUP:NB",         label: "NB",         group: "NGX", description: "Nigerian Breweries" },
  { tv: "NGXGROUP:NESTLE",     label: "NESTLE",     group: "NGX", description: "Nestlé Nigeria" },
  { tv: "NGXGROUP:PRESCO",     label: "PRESCO",     group: "NGX", description: "Presco PLC" },
  { tv: "NGXGROUP:OKOMUOIL",   label: "OKOMUOIL",   group: "NGX", description: "Okomu Oil Palm" },
  { tv: "NGXGROUP:FLOURMILL",  label: "FLOURMILL",  group: "NGX", description: "Flour Mills of Nigeria" },
  { tv: "NGXGROUP:DANGSUGAR",  label: "DANGSUGAR",  group: "NGX", description: "Dangote Sugar Refinery" },
  { tv: "NGXGROUP:CADBURY",    label: "CADBURY",    group: "NGX", description: "Cadbury Nigeria" },
  { tv: "NGXGROUP:UNILEVER",   label: "UNILEVER",   group: "NGX", description: "Unilever Nigeria" },
  { tv: "NGXGROUP:GUINNESS",   label: "GUINNESS",   group: "NGX", description: "Guinness Nigeria" },
  { tv: "NGXGROUP:INTBREW",    label: "INTBREW",    group: "NGX", description: "International Breweries" },
  { tv: "NGXGROUP:NASCON",     label: "NASCON",     group: "NGX", description: "NASCON Allied Industries" },
  { tv: "NGXGROUP:CONOIL",     label: "CONOIL",     group: "NGX", description: "Conoil PLC" },
  { tv: "NGXGROUP:OANDO",      label: "OANDO",      group: "NGX", description: "Oando PLC" },
  { tv: "NGXGROUP:GEREGU",     label: "GEREGU",     group: "NGX", description: "Geregu Power" },
  { tv: "NGXGROUP:TRANSCOHOT", label: "TRANSCOHOT", group: "NGX", description: "Transcorp Hotels" },
  { tv: "NGXGROUP:BERGER",     label: "BERGER",     group: "NGX", description: "Berger Paints Nigeria" },
  { tv: "NGXGROUP:FIDSON",     label: "FIDSON",     group: "NGX", description: "Fidson Healthcare" },
  { tv: "NGXGROUP:MAYBAKER",   label: "MAYBAKER",   group: "NGX", description: "May & Baker Nigeria" },
  { tv: "NGXGROUP:PZ",         label: "PZ",         group: "NGX", description: "PZ Cussons Nigeria" },
  { tv: "NGXGROUP:WAPCO",      label: "WAPCO",      group: "NGX", description: "Lafarge Africa (WAPCO)" },
  { tv: "NGXGROUP:CUSTODIAN",  label: "CUSTODIAN",  group: "NGX", description: "Custodian Investment" },
  { tv: "NGXGROUP:JBERGER",    label: "JBERGER",    group: "NGX", description: "Julius Berger Nigeria" },
  { tv: "NGXGROUP:CCNN",       label: "CCNN",       group: "NGX", description: "CCNN (Sokoto Cement)" },
  { tv: "NGXGROUP:LIVESTOCK",  label: "LIVESTOCK",  group: "NGX", description: "Livestock Feeds" },
  { tv: "NGXGROUP:NEIMETH",    label: "NEIMETH",    group: "NGX", description: "Neimeth International Pharma" },
  { tv: "NGXGROUP:CHAMS",      label: "CHAMS",      group: "NGX", description: "Chams Holding Company" },
  { tv: "NGXGROUP:HONYFLOUR",  label: "HONYFLOUR",  group: "NGX", description: "Honeywell Flour Mills" },
  { tv: "NGXGROUP:CAPHOTEL",   label: "CAPHOTEL",   group: "NGX", description: "Capital Hotel" },
  { tv: "NGXGROUP:LINKASSURE", label: "LINKASSURE", group: "NGX", description: "Linkage Assurance" },
  { tv: "NGXGROUP:CILEASING",  label: "CILEASING",  group: "NGX", description: "C&I Leasing" },
];

/** Symbol lookup by short label */
export function tvSymbol(label: string): string {
  return (
    TV_SYMBOLS.find(
      (s) => s.label === label ||
             s.label === label.replace("USDT", "/USDT") ||
             s.label.replace("/", "") === label
    )?.tv ?? `NASDAQ:${label}`
  );
}

/** Ticker tape symbols for the scrolling strip — limit to 30 liquid names */
export const TICKER_TAPE_SYMBOLS = TV_SYMBOLS
  .filter((s) => ["Stocks", "ETFs", "Crypto"].includes(s.group))
  .slice(0, 30)
  .map((s) => ({ proName: s.tv, title: s.label }));

/** Base dark theme config shared across all widgets */
export const TV_THEME = {
  colorTheme: "dark",
  locale: "en",
} as const;
